"""
Central behaviour-opportunity definitions for worksheet bundles.

Maps rubric item IDs to Observable Behaviour (OB_*) candidates only.
No ILO, Domain, or AI-CFT references are permitted in this module.
"""

from __future__ import annotations

from typing import Any

OB_REF = "framework/Observable_Behaviours.json"

# ProDaBi unplugged worksheets with legacy rubrics in rubrics/ (no WS2, WS8, WS9).
ALL_WORKSHEETS: tuple[str, ...] = (
    "WS1",
    "WS3",
    "WS4",
    "WS5",
    "WS6",
    "WS7",
    "WS10",
    "WS11",
)

# CODAP / plugged worksheet bundles (hand-maintained; not generated by build_worksheet_bundles.py).
CODAP_WORKSHEETS: frozenset[str] = frozenset({"WS_DT"})

# All worksheet directories under worksheets/ that must pass bundle validation.
BUNDLE_WORKSHEETS: tuple[str, ...] = ALL_WORKSHEETS + tuple(sorted(CODAP_WORKSHEETS))

DEPLOYED_WORKSHEETS: frozenset[str] = frozenset(ALL_WORKSHEETS) | CODAP_WORKSHEETS

BUNDLE_FILES: tuple[str, ...] = (
    "extraction_schema.json",
    "rubric.json",
    "behaviour_opportunities.json",
    "validity_notes.json",
    "answer_key.json",
)

FORBIDDEN_SUBSTRINGS: tuple[str, ...] = (
    "lo3",
    "ilo_id",
    "learning_object",
    "domain_id",
    "ai_cft",
    "ai-cft",
    "competency",
    "maps_to",
    "may_contribute_to",
    "may_indicate",
)


def _opp(
    behaviour_id: str,
    *,
    role: str = "primary",
    evidence_mode: str = "direct",
    rationale: str,
) -> dict[str, str]:
    return {
        "behaviour_id": behaviour_id,
        "role": role,
        "evidence_mode": evidence_mode,
        "rationale": rationale,
    }


def _item(
    opportunities: list[dict[str, str]],
    extraction_fields: list[str] | None = None,
) -> dict[str, Any]:
    out: dict[str, Any] = {"opportunities": opportunities}
    if extraction_fields:
        out["extraction_fields"] = extraction_fields
    return out


# ---------------------------------------------------------------------------
# Per-worksheet behaviour opportunity maps (rubric item key → OB candidates)
# ---------------------------------------------------------------------------

BEHAVIOUR_MAP: dict[str, dict[str, dict[str, Any]]] = {
    "WS1": {
        "WS1_B1": _item([_opp("OB_CON_001", rationale="Uses variable/label term (değişken or etiket) in nutrition-label context.")]),
        "WS1_B2": _item([_opp("OB_CON_001", rationale="Uses object/feature term (nesne or özellik) for a food instance.")]),
        "WS1_B3": _item([_opp("OB_CON_001", rationale="Names feature term; accepts nesne|özellik or değişken|etiket equivalents.")]),
        "WS1_B4": _item([_opp("OB_CON_001", rationale="Counts features in the nutrition table.")]),
        "WS1_B5": _item([_opp("OB_CON_001", rationale="Lists nutrient feature names from the table.")]),
        "WS1_B6": _item([_opp("OB_CON_001", rationale="Identifies the example food object on the sheet.")]),
        "WS1_B7": _item([_opp("OB_CON_001", rationale="Uses label (etiket) role for recommendation outcome.")]),
    },
    "WS3": {
        "WS3_B1": _item([_opp("OB_PRO_001", rationale="Applies Leo's rule to classify instance 1."),
                         _opp("OB_PRO_006", role="secondary", evidence_mode="direct",
                              rationale="Assigns recommended/not-recommended label.")]),
        "WS3_B2": _item([_opp("OB_PRO_001", rationale="Justifies classification using feature value."),
                         _opp("OB_STR_001", role="secondary", evidence_mode="direct",
                              rationale="Links feature to threshold comparison in reasoning.")]),
        "WS3_B3": _item([_opp("OB_PRO_001", rationale="Applies Leo's rule to classify instance 2."),
                         _opp("OB_PRO_006", role="secondary", evidence_mode="direct",
                              rationale="Assigns recommended label.")]),
        "WS3_B4": _item([_opp("OB_PRO_001", rationale="Justifies recommended classification."),
                         _opp("OB_STR_001", role="secondary", evidence_mode="direct",
                              rationale="Threshold comparison in verbal reasoning.")]),
        "WS3_B5": _item([_opp("OB_PRO_001", rationale="Applies Leo's rule to classify instance 3."),
                         _opp("OB_PRO_006", role="secondary", evidence_mode="direct",
                              rationale="Assigns not-recommended label.")]),
        "WS3_B6": _item([_opp("OB_PRO_001", rationale="Justifies not-recommended classification."),
                         _opp("OB_STR_001", role="secondary", evidence_mode="direct",
                              rationale="Feature-threshold reasoning statement.")]),
        "WS3_B7": _item([_opp("OB_PRO_007", rationale="Student sets energy threshold with operator."),
                         _opp("OB_STR_002", role="secondary", evidence_mode="direct",
                              rationale="Threshold direction encodes split semantics.")]),
        "WS3_B8": _item([_opp("OB_PRO_007", rationale="Complementary threshold branch for energy feature."),
                         _opp("OB_STR_002", role="secondary", evidence_mode="direct",
                              rationale="Operator direction must pair with B7.")]),
    },
    "WS4": {
        "WS4_B1": _item([_opp("OB_PRO_007", rationale="Places improved threshold between avocado and french fries."),
                         _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                              rationale="Threshold boundary informed by sorted food-card values.")]),
        "WS4_B2": _item([_opp("OB_PRO_008", rationale="Identifies all four misclassified foods at prior threshold."),
                         _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                              rationale="Links misclassification pattern to threshold position.")]),
        "WS4_B3": _item([_opp("OB_STR_003", rationale="Reflects that misclassification decreased after new threshold."),
                         _opp("OB_REF_003", role="secondary", evidence_mode="direct",
                              rationale="Evaluates performance improvement claim.")]),
        "WS4_B4": _item([_opp("OB_REF_002", rationale="Evaluates Pia's claim about equal fat values blocking a split."),
                         _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                              rationale="Connects equal feature values to threshold placement.")]),
        "WS4_B5": _item([_opp("OB_PRO_007", rationale="States learned energy threshold from food cards."),
                         _opp("OB_STR_001", role="secondary", evidence_mode="direct",
                              rationale="Data-based parameter choice in valid numeric range.")]),
    },
    "WS5": {
        "WS5_row1": _item([_opp("OB_PRO_007", rationale="Threshold expression in grid row 1."),
                           _opp("OB_PRO_008", role="secondary", evidence_mode="direct",
                                rationale="Correct/error counts for row 1."),
                           _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                                rationale="MCR consistency for row 1.")]),
        "WS5_row2": _item([_opp("OB_PRO_007", rationale="Threshold expression in grid row 2."),
                           _opp("OB_PRO_008", role="secondary", evidence_mode="direct",
                                rationale="Correct/error counts for row 2."),
                           _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                                rationale="MCR consistency for row 2.")]),
        "WS5_row3": _item([_opp("OB_PRO_007", rationale="Threshold expression in grid row 3."),
                           _opp("OB_PRO_008", role="secondary", evidence_mode="direct",
                                rationale="Correct/error counts for row 3."),
                           _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                                rationale="MCR consistency for row 3.")]),
        "WS5_row4": _item([_opp("OB_PRO_007", rationale="Threshold expression in grid row 4."),
                           _opp("OB_PRO_008", role="secondary", evidence_mode="direct",
                                rationale="Correct/error counts for row 4."),
                           _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                                rationale="MCR consistency for row 4.")]),
        "WS5_row5": _item([_opp("OB_PRO_007", rationale="Threshold expression in grid row 5."),
                           _opp("OB_PRO_008", role="secondary", evidence_mode="direct",
                                rationale="Correct/error counts for row 5."),
                           _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                                rationale="MCR consistency for row 5.")]),
        "WS5_B25": _item([_opp("OB_PRO_007", rationale="Final threshold choice from experiment."),
                          _opp("OB_STR_001", role="secondary", evidence_mode="direct",
                               rationale="Data-based justification for chosen threshold.")],
                         extraction_fields=["WS5_B25"]),
    },
    "WS6": {
        "WS6_root_feature": _item([_opp("OB_PRO_002", rationale="Selects root split feature.")],
                                  extraction_fields=["WS6_B1"]),
        "WS6_root_threshold": _item([_opp("OB_PRO_007", rationale="Root threshold with operator."),
                                     _opp("OB_STR_002", role="secondary", evidence_mode="direct",
                                          rationale="Split direction at root.")],
                                    extraction_fields=["WS6_B2"]),
        "WS6_root_labels": _item([_opp("OB_PRO_003", rationale="Branch labels at root node.")],
                                   extraction_fields=["WS6_B3", "WS6_B4"]),
        "WS6_inner_feature": _item([_opp("OB_PRO_002", rationale="Inner-node feature distinct from root.")],
                                   extraction_fields=["WS6_B6"]),
        "WS6_inner_threshold": _item([_opp("OB_PRO_007", rationale="Inner-node threshold with operator."),
                                      _opp("OB_STR_002", role="secondary", evidence_mode="direct",
                                           rationale="Inner split direction.")],
                                     extraction_fields=["WS6_B7"]),
        "WS6_inner_labels": _item([_opp("OB_PRO_003", rationale="Branch labels at inner node.")],
                                    extraction_fields=["WS6_B8", "WS6_B9"]),
        "WS6_leaves": _item([_opp("OB_PRO_006", rationale="Leaf class labels on tree paths."),
                             _opp("OB_PRO_004", role="secondary", evidence_mode="direct",
                                  rationale="Leaf labels consistent with path logic.")],
                            extraction_fields=["WS6_B5", "WS6_B10", "WS6_B11", "WS6_B12", "WS6_B13"]),
        "WS6_tree_structure": _item([_opp("OB_PRO_005", rationale="Holistic tree validity (depth, features, leaves)."),
                                     _opp("OB_STR_004", role="secondary", evidence_mode="direct",
                                          rationale="Structural coherence of drawn tree.")]),
    },
    "WS7": {
        "WS7_P1_box1": _item([_opp("OB_PRO_003", rationale="Matches given rule to tree path A/B/C.")],
                             extraction_fields=["WS7_P1_box1"]),
        "WS7_P1_box2": _item([_opp("OB_PRO_003", rationale="Matches given rule to tree path.")],
                             extraction_fields=["WS7_P1_box2"]),
        "WS7_P1_box3": _item([_opp("OB_PRO_003", rationale="Matches given rule to tree path.")],
                             extraction_fields=["WS7_P1_box3"]),
        "WS7_B1": _item([_opp("OB_PRO_009", rationale="Writes if-then rule consistent with WS6 tree path."),
                         _opp("OB_STR_006", role="secondary", evidence_mode="direct",
                              rationale="Rule encodes feature, operator, and conclusion.")],
                        extraction_fields=["WS7_B1"]),
        "WS7_B2": _item([_opp("OB_PRO_009", rationale="Second path rule consistent with WS6 tree."),
                         _opp("OB_STR_006", role="secondary", evidence_mode="direct",
                              rationale="Conditional structure for path B.")],
                        extraction_fields=["WS7_B2"]),
        "WS7_B3": _item([_opp("OB_PRO_009", rationale="Third path rule consistent with WS6 tree."),
                         _opp("OB_STR_006", role="secondary", evidence_mode="direct",
                              rationale="Conditional structure for path C.")],
                        extraction_fields=["WS7_B3"]),
    },
    "WS10": {
        "WS10_B1": _item([_opp("OB_PRO_008", rationale="Misclassification count at printed threshold row 1 (28).")]),
        "WS10_B2": _item([_opp("OB_PRO_008", rationale="Misclassification count at row 2 (69).")]),
        "WS10_B3": _item([_opp("OB_PRO_008", rationale="Misclassification count at row 3 (219).")]),
        "WS10_B4": _item([_opp("OB_PRO_008", rationale="Misclassification count at row 4 (346).")]),
        "WS10_B5": _item([_opp("OB_PRO_008", rationale="Misclassification count at row 5 (359).")]),
        "WS10_B6": _item([_opp("OB_PRO_008", rationale="Misclassification count at row 6 (408) — minimum.")]),
        "WS10_B7": _item([_opp("OB_PRO_008", rationale="Misclassification count at row 7 (489).")]),
        "WS10_B8": _item([_opp("OB_PRO_007", rationale="Selects optimum threshold with minimum misclassifications."),
                          _opp("OB_STR_003", role="secondary", evidence_mode="direct",
                               rationale="Systematic comparison across grid rows.")]),
    },
    "WS11": {
        "WS11_B8a": _item([_opp("OB_PRO_001", rationale="Classifies instance using peer tree."),
                           _opp("OB_PRO_006", role="secondary", evidence_mode="direct",
                                rationale="Not-recommended label assignment.")]),
        "WS11_B8b": _item([_opp("OB_PRO_009", rationale="States if-then rule for classification path."),
                           _opp("OB_STR_006", role="secondary", evidence_mode="direct",
                                rationale="Conditional rule structure.")]),
        "WS11_B9": _item([_opp("OB_CON_004", rationale="Defines decision tree concept."),
                          _opp("OB_REF_001", role="secondary", evidence_mode="direct",
                               rationale="Reflective definition of model type.")]),
        "WS11_Q10_1": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 1.")]),
        "WS11_Q10_2": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 2.")]),
        "WS11_Q10_3": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 3.")]),
        "WS11_Q10_4": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 4.")]),
        "WS11_Q10_5": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 5.")]),
        "WS11_Q10_6": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 6.")]),
        "WS11_Q10_7": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 7.")]),
        "WS11_Q10_8": _item([_opp("OB_REF_001", rationale="True/false on model purpose statement 8.")]),
        "WS11_Q11_2": _item([_opp("OB_STR_007", rationale="Ordering step 2 in tree-building procedure.")]),
        "WS11_Q11_3": _item([_opp("OB_STR_007", rationale="Ordering step 3 in tree-building procedure.")]),
        "WS11_Q11_4": _item([_opp("OB_STR_007", rationale="Ordering step 4 in tree-building procedure.")]),
        "WS11_Q12_1": _item([_opp("OB_REF_003", rationale="Multiselect: identifies valid tree-building actions.")]),
        "WS11_Q12_2": _item([_opp("OB_REF_003", rationale="Multiselect: identifies valid tree-building actions.")]),
        "WS11_Q12_3": _item([_opp("OB_REF_003", rationale="Multiselect: identifies valid tree-building actions.")]),
        "WS11_Q12_4": _item([_opp("OB_REF_003", rationale="Multiselect: identifies valid tree-building actions.")]),
        "WS11_Q12_5": _item([_opp("OB_REF_003", rationale="Multiselect: identifies valid tree-building actions.")]),
    },
}


VALIDITY_NOTES: dict[str, dict[str, Any]] = {
    "WS1": {
        "construct_threats": [
            "Fill-in recall may conflate vocabulary with procedural competence.",
            "Feature count must be 7 or yedi (nutrition table rows); 8/sekiz is not accepted.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "No authentic data manipulation; label-diagram task only.",
            "Short answers accept WS1 equivalence pairs: nesne|özellik and değişken|etiket.",
        ],
        "cross_worksheet_dependencies": [],
    },
    "WS3": {
        "construct_threats": [
            "Part 1 applies a fixed peer rule; does not test independent rule invention.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "B7/B8 threshold values are student-chosen; no single numeric key.",
        ],
        "cross_worksheet_dependencies": [],
    },
    "WS4": {
        "construct_threats": [
            "B1 threshold line is primarily visual; OCR may miss drawn placement.",
            "B2 food marks on images may be transcribed incompletely.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "Handwriting variance — semantic items tolerate gist; B2 requires all four foods.",
            "B4 rejects meta peer commentary without same-fat-value reasoning.",
            "B5 accepts any energy threshold from 160 to 2223 inclusive.",
        ],
        "cross_worksheet_dependencies": [],
    },
    "WS5": {
        "construct_threats": [
            "Grid filling is procedural; students may copy arithmetic patterns without recounting cards.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "Row-level scoring aggregates four cells; cell-level evidence is not separately scored.",
            "Reference counts computed dynamically from data/prodabi_food_cards.csv (N=11); no fixed threshold answer key.",
            "Partial row credit (0.5) when notation and arithmetic are valid but classification counts mismatch the dataset.",
        ],
        "cross_worksheet_dependencies": [
            {"depends_on": "WS4", "reason": "Students apply threshold search insights on the same food-card set."},
        ],
    },
    "WS6": {
        "construct_threats": [
            "Drawn tree quality depends on OCR field capture fidelity.",
            "Holistic tree_structure may double-count threshold/leaf issues.",
            "Students may use two levels even when MCR=0 — not a construct threat.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "13 OCR fields may not capture full spatial layout; vision crop optional.",
            "MCR and path logic computed dynamically from student's tree over prodabi cards (N=11); no fixed tree answer key.",
            "Partial credit on threshold/labels when complementary operator pairs mismatch.",
        ],
        "cross_worksheet_dependencies": [
            {"depends_on": "WS5", "reason": "Same 11 food cards; WS5 explores thresholds WS6 implements as tree."},
            {"depends_on": "WS7", "reason": "WS7 rules graded for consistency with this tree."},
        ],
    },
    "WS7": {
        "construct_threats": [
            "Part 1 path matching uses a fixed enerji/protein sample tree, not the student's WS6 tree.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "B4–B7 marked not_applicable when tree has only three leaf paths.",
            "Part 2 operators (< > ≤ ≥) must match WS6 branches exactly; validated in ws7_validation.py.",
        ],
        "cross_worksheet_dependencies": [
            {"depends_on": "WS6", "reason": "B1–B3 rules must match WS6 path operators, thresholds, and leaf labels."},
        ],
    },
    "WS10": {
        "construct_threats": [
            "Numeric table region may be blocked if OCR/HTR fails to capture grid.",
        ],
        "leakage_risks": [],
        "evidence_limitations": [
            "Fixed ProDaBi v4 dataset — answers are exact integers from data/ws10_energy_reference.json.",
            "Printed thresholds are not scored; only misclassification counts (B1–B7) and optimum (B8).",
        ],
        "cross_worksheet_dependencies": [],
    },
    "WS11": {
        "construct_threats": [
            "Printed Q1–Q7 (survey + demographics) and Likert items are descriptive_only; must not infer competence.",
        ],
        "leakage_risks": [
            "Demographic items (B6–B7, L12) must never enter behaviour or ILO inference.",
        ],
        "evidence_limitations": [
            "Only cognitive scored items (B8a, B8b, B9, Q10, Q11, Q12) produce behaviour evidence.",
            "Q1–Q5 (B1–B5) and Q6–Q7 (B6–B7) have no keyed correct answers — store verbatim only.",
        ],
        "cross_worksheet_dependencies": [],
        "descriptive_only_items": [
            "WS11_B1", "WS11_B2", "WS11_B3", "WS11_B4", "WS11_B5", "WS11_B6", "WS11_B7",
            "WS11_L10", "WS11_L11", "WS11_L12",
        ],
    },
}


EXTRACTION_NOTES: dict[str, str] = {
    "WS1": "Seven fill-in-the-blank fields on the nutrition label (WS1_B1–B7; printed blanks 5–11).",
    "WS3": "Eight response fields; B7/B8 are threshold expressions.",
    "WS4": "Five response fields (B1–B5): threshold line, four-food identification, improvement reflection, Pia evaluation, energy threshold.",
    "WS5": "Twenty-five table cells (B1–B25) plus six aggregate row keys.",
    "WS6": "Thirteen structured tree fields (WS6_B1–B13).",
    "WS7": "Part 1: three path-letter boxes (P1_box1–3). Part 2: if-then rules B1–B3 vs WS6 tree.",
    "WS10": "Seven table misclassification counts (B1–B7) + optimum threshold blank (B8).",
    "WS11": "Printed Q1–Q7 (B1–B5 survey/Likert, B6–B7 demographics; no correct answer). B8a–B9 + Q10–Q12 cognitive (scored). L10–L12 Likert/descriptive only.",
}
